version: '3.8'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - C:\Users\ighos\Documents\vscode\Monologue\nginx.conf:/etc/nginx/nginx.conf
      - C:\Users\ighos\Documents\vscode\Monologue\nginx.conf:/etc/nginx/conf.d/default.conf
      - C:\Users\ighos\Documents\vscode\Monologue:/usr/share/nginx/html
  mongodb:
    image: mongo:6.0.2
#    container_name: 'mongodb'
    restart: always
    ports: 
      - 27019:27017
  spring-boot:
    build: .
#    container_name: 'mono'
    restart: always
    ports:
      - 8080:8080